services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: soil-segment-backend
    ports:
      - "9000:8000"   # external:internal
    volumes:
      - ./models:/app/backend/models:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
